name = "triple-ema"

[emas]
field = "close"
fast_period = 13
medium_period = 26
slow_period = 52

[market_data]
timeframe_1 = "5m"  # TREND_1
timeframe_2 = "3m"  # TREND_2
timeframe_3 = "1m"  # SIGNAL (também definido como heartbeat pelo método rhythm_slot)
timeframe_4 = ""    # AUX_1
since = ""
candle_limit = 150

